name: pre-commit
on: workflow_call
jobs:
    pre-commit_workflow_job:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v3
        - name: Run pre-commit checks
          run: npm run pre-commit
          working-directory: ./src
          continue-on-error: true