name: pre-commit
on: workflow_call
jobs:
    release_workflow_job:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v3
        - uses: softprops/action-gh-release@v0.1.15