# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: test and build
on:

  push:
    branches: ['main']

  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  test:
    uses: ./.github/workflows/test.yml
    secrets: inherit


  sca:
    uses: ./.github/workflows/sca.yml
  
  chatgpt:
    uses: ./.github/workflows/chatgpt.yml

  pre-commit:
    uses: ./.github/workflows/pre-commit.yml

  build:
    uses: ./.github/workflows/build.yml
    needs: [test, sca, chatgpt, pre-commit]